# Google Cloud Build configuration for automated deployment
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/llm-reliability-control-plane:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/llm-reliability-control-plane:latest'
      - '.'
    id: 'build-image'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/llm-reliability-control-plane'
    id: 'push-image'
    waitFor: ['build-image']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'llm-reliability-control-plane'
      - '--image'
      - 'gcr.io/$PROJECT_ID/llm-reliability-control-plane:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - |
        DD_SERVICE=llm-reliability-control-plane,
        DD_ENV=production,
        DD_VERSION=$SHORT_SHA,
        DD_LLMOBS_AGENTLESS_ENABLED=1,
        DD_TRACE_ENABLED=true,
        DD_LOGS_ENABLED=true,
        DD_SITE=us5.datadoghq.com,
        LRCP_GCP_PROJECT_ID=llm-reliability-control
      - '--set-secrets'
      - |
          LRCP_GEMINI_API_KEY=gemini-api-key:latest,
          LRCP_DATADOG_API_KEY=datadog-api-key:latest,
          DD_APP_KEY=datadog-app-key:latest,
          LRCP_GCP_PROJECT_ID=gcp-project-id:latest
    id: 'deploy-cloud-run'
    waitFor: ['push-image']

# Substitution variables (set in Cloud Build triggers)
substitutions:
  _REGION: us-central1

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout for the entire build
timeout: '1200s'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/llm-reliability-control-plane:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/llm-reliability-control-plane:latest'

