"""
API Key Configuration Script

Sets up Datadog API keys for the application.
This script helps configure environment variables for Datadog integration.

Usage:
    python scripts/setup_api_keys.py
"""

import os
import sys
from pathlib import Path

# Datadog API keys (provided by user)
DD_API_KEY = "e38221fb258a4ea3ec8bd312db36fa6e"
DD_APP_KEY = "ef51694759c084b54ecd2ced19579924c9eb968c"


def setup_env_file():
    """Create or update .env file with API keys."""
    env_file = Path(__file__).parent.parent / ".env"
    
    env_content = f"""# Datadog API Configuration
# Generated by setup_api_keys.py

# Datadog API Key
DD_API_KEY={DD_API_KEY}
LRCP_DATADOG_API_KEY={DD_API_KEY}

# Datadog Application Key
DD_APP_KEY={DD_APP_KEY}

# Datadog Site (default: datadoghq.com)
DD_SITE=datadoghq.com

# Datadog Agent Host (default: localhost)
DD_AGENT_HOST=localhost

# Datadog Agent Ports
DD_DOGSTATSD_PORT=8125
DD_TRACE_AGENT_PORT=8126

# Enable Datadog features
DD_TRACE_ENABLED=true
DD_LOGS_ENABLED=true
"""
    
    # Check if .env exists
    if env_file.exists():
        print(f"WARNING: .env file already exists: {env_file}")
        # Auto-overwrite for automation
        print("   Auto-overwriting existing .env file...")
    
    # Write .env file
    try:
        env_file.write_text(env_content)
        print(f"SUCCESS: Created .env file: {env_file}")
        return True
    except Exception as e:
        print(f"ERROR: Error creating .env file: {e}")
        return False


def setup_environment_variables():
    """Set environment variables in current session."""
    print("\n2. Setting environment variables for current session...")
    
    os.environ['DD_API_KEY'] = DD_API_KEY
    os.environ['LRCP_DATADOG_API_KEY'] = DD_API_KEY
    os.environ['DD_APP_KEY'] = DD_APP_KEY
    os.environ['DD_SITE'] = 'datadoghq.com'
    os.environ['DD_AGENT_HOST'] = 'localhost'
    os.environ['DD_TRACE_ENABLED'] = 'true'
    os.environ['DD_LOGS_ENABLED'] = 'true'
    
    print("SUCCESS: Environment variables set for current session")
    print("  Note: These will be lost when you close the terminal")
    print("  Use .env file or export commands for persistence")


def print_manual_setup():
    """Print manual setup instructions."""
    print("\n3. Manual Setup Instructions:")
    print("=" * 60)
    
    print("\nWindows PowerShell:")
    print("  $env:DD_API_KEY = \"" + DD_API_KEY + "\"")
    print("  $env:DD_APP_KEY = \"" + DD_APP_KEY + "\"")
    print("  $env:LRCP_DATADOG_API_KEY = \"" + DD_API_KEY + "\"")
    
    print("\nLinux/macOS:")
    print("  export DD_API_KEY=\"" + DD_API_KEY + "\"")
    print("  export DD_APP_KEY=\"" + DD_APP_KEY + "\"")
    print("  export LRCP_DATADOG_API_KEY=\"" + DD_API_KEY + "\"")
    
    print("\nOr use python-dotenv to load .env file:")
    print("  from dotenv import load_dotenv")
    print("  load_dotenv()")


def verify_keys():
    """Verify API keys are set."""
    print("\n4. Verifying API keys...")
    
    api_key = os.getenv('DD_API_KEY') or os.getenv('LRCP_DATADOG_API_KEY')
    app_key = os.getenv('DD_APP_KEY')
    
    if api_key and app_key:
        print(f"SUCCESS: DD_API_KEY: {api_key[:10]}...{api_key[-10:]}")
        print(f"SUCCESS: DD_APP_KEY: {app_key[:10]}...{app_key[-10:]}")
        return True
    else:
        print("ERROR: API keys not set in environment")
        print("  Run this script or set manually")
        return False


def main():
    """Main setup function."""
    print("=" * 60)
    print("Datadog API Key Configuration")
    print("=" * 60)
    
    # Setup .env file
    print("\n1. Creating .env file...")
    setup_env_file()
    
    # Setup environment variables
    setup_environment_variables()
    
    # Print manual instructions
    print_manual_setup()
    
    # Verify
    verify_keys()
    
    print("\n" + "=" * 60)
    print("Setup Complete! SUCCESS")
    print("=" * 60)
    print("\nNext steps:")
    print("  1. Train ML models: python scripts/train_models.py")
    print("  2. Start the server: python -m uvicorn app.main:app --reload")
    print("  3. Access Swagger UI: http://127.0.0.1:8000/docs")
    print("\nNote: If using .env file, install python-dotenv:")
    print("  pip install python-dotenv")
    
    return 0


if __name__ == "__main__":
    exit_code = main()
    sys.exit(exit_code)

